import { Type } from "@sinclair/typebox";
import { Value } from "@sinclair/typebox/value";
import type { ChapterPacket, GenreConfig, PlotGridState } from "../domain/schemas.js";
import type { NovelProfile, ProfileFinding } from "./types.js";
const requiredProfileFields = ["fantasy_movement", "romance_movement", "trust_delta", "desire_conflict", "power_balance", "consent_state"] as const;
const profileFieldsSchema = Type.Object({ fantasy_movement: Type.String({ minLength: 1 }), romance_movement: Type.String({ minLength: 1 }), trust_delta: Type.String({ minLength: 1 }), desire_conflict: Type.String({ minLength: 1 }), power_balance: Type.String({ minLength: 1 }), consent_state: Type.String({ minLength: 1 }) }, { additionalProperties: true });
const genreSettingsSchema = Type.Object({ story_balance: Type.Union([Type.Literal("romance-primary"), Type.Literal("balanced"), Type.Literal("fantasy-primary")]), romance_contract: Type.Union([Type.Literal("central"), Type.Literal("major")]), ending_contract: Type.Union([Type.Literal("hea"), Type.Literal("hfn"), Type.Literal("series-progress"), Type.Literal("tragic-by-design")]), heat_level: Type.Union([Type.Literal("closed-door"), Type.Literal("fade-to-black"), Type.Literal("open-door"), Type.Literal("explicit")]), fantasy_scale: Type.Union([Type.Literal("intimate"), Type.Literal("regional"), Type.Literal("epic")]), point_of_view: Type.Union([Type.Literal("single"), Type.Literal("dual"), Type.Literal("multi")]), relationship_structure: Type.Union([Type.Literal("monogamous"), Type.Literal("polyamorous"), Type.Literal("why-choose")]) }, { additionalProperties: false });
const genreRequirementsSchema = Type.Object({ protagonist_independent_goal: Type.Boolean(), character_specific_attraction: Type.Boolean(), explicit_consent_logic: Type.Boolean(), magic_cost: Type.Boolean(), fantasy_conflict_resolution: Type.Boolean(), declared_ending_contract: Type.Boolean() }, { additionalProperties: false });
function schemaFinding(schema: object, value: unknown, category: string): ProfileFinding[] { return Value.Check(schema as never, value) ? [] : [{ severity: "blocker", category, message: `Invalid ${category} values for the romantasy profile.` }]; }
function packetFieldFindings(packet: ChapterPacket): ProfileFinding[] { return requiredProfileFields.flatMap((field) => typeof packet.profile_fields[field] === "string" && String(packet.profile_fields[field]).trim() ? [] : [{ severity: "blocker" as const, category: "romantasy-packet", message: `Missing or invalid romantasy packet field: ${field}` }]); }
export const romantasyProfile: NovelProfile = {
  id: "romantasy", label: "Romantasy", profileFieldsSchema, genreSettingsSchema, genreRequirementsSchema,
  defaultGenreConfig() { return { schema_version: "1.0.0", profile: "romantasy", settings: { story_balance: "balanced", romance_contract: "central", ending_contract: "series-progress", heat_level: "open-door", fantasy_scale: "epic", point_of_view: "dual", relationship_structure: "monogamous" }, requirements: { protagonist_independent_goal: true, character_specific_attraction: true, explicit_consent_logic: true, magic_cost: true, fantasy_conflict_resolution: true, declared_ending_contract: true } }; },
  planningQuestions: ["Is the book romance-primary, balanced, or fantasy-primary?", "What ending contract applies: HEA, HFN, series-progress, or tragic-by-design?", "Why are these characters specifically attracted to each other beyond appearance or destiny?", "What values, secrets, duties, or wounds make them genuinely incompatible?", "How do trust, intimacy, allegiance, and power balance change through the book?", "What are the rules, costs, and limits of magic, especially where magic touches intimacy or bonding?", "How does the romantic rupture alter the fantasy plot, and how does the fantasy climax test the relationship?"],
  chapterPacketRequirements: requiredProfileFields,
  milestoneReviewLanes: ["romantic arc and emotional causality", "fantasy plot and worldbuilding", "magic continuity and cost", "consent, power, and intimacy logic", "character independence and relationship differentiation", "voice, chemistry, dialogue, and line quality", "romance/fantasy pacing balance"],
  draftingRules: ["Keep both protagonists active outside the relationship.", "Build attraction from observation, friction, competence, vulnerability, and values.", "Treat consent and power asymmetry as scene logic, not a late disclaimer.", "Do not let magic automatically solve emotional conflict.", "Make rupture follow established choices or values rather than a removable misunderstanding.", "Advance fantasy and romance arcs in relation, without requiring every scene to advance both equally."],
  validatePacket(packet: ChapterPacket) { const findings = packetFieldFindings(packet); if (!packet.relationship_movement.trim() && !packet.profile_fields["romance_movement"]) findings.push({ severity: "high", category: "romance-arc", message: "Romantasy packet does not define relationship movement." }); return findings; },
  validateGenreConfig(config: GenreConfig) { if (config.profile !== "romantasy") return [{ severity: "blocker", category: "genre", message: "Genre profile is not romantasy." }]; return [...schemaFinding(genreSettingsSchema, config.settings, "romantasy settings"), ...schemaFinding(genreRequirementsSchema, config.requirements, "romantasy requirements")]; },
  validatePlot(plot: PlotGridState) { const findings: ProfileFinding[] = []; if (!plot.chapters.length) findings.push({ severity: "blocker", category: "architecture", message: "Romantasy plot grid has no chapters." }); if (plot.chapters.some((chapter) => !chapter.state_change.trim() || /^none$/i.test(chapter.state_change))) findings.push({ severity: "high", category: "causality", message: "Romantasy plot contains a no-state-change chapter." }); const obligations = plot.chapters.flatMap((chapter) => chapter.profile_obligations); if (!obligations.some((item) => /romance|trust|intimacy/i.test(item))) findings.push({ severity: "high", category: "romance-arc", message: "Plot grid does not track romance progression." }); if (!obligations.some((item) => /fantasy|magic|quest|politic/i.test(item))) findings.push({ severity: "high", category: "fantasy-arc", message: "Plot grid does not track fantasy progression." }); if (!obligations.some((item) => /rupture|separation|betrayal|break/i.test(item))) findings.push({ severity: "high", category: "rupture", message: "Plot grid does not identify an earned relationship rupture or equivalent late pressure." }); return findings; },
  endingRules: ["Honor the declared romance ending contract.", "Resolve the fantasy conflict on its own causal terms.", "Do not use intimacy as a substitute for trust repair.", "Preserve earned emotional payoff even when a series pressure remains open."],
};
