from pathlib import Path
FILES = {
    'evals/v1-3-release/agency-tracking.yaml': 'schema_version: 1.0.0\nid: agency-tracking\nkind: agency-tracking\ninput:\n  decision:\n    chapter: 2\n    choice: Mara enters the restricted archive.\n    immediate_gain: She obtains the missing log.\n    deferred_cost: Security now tracks her.\n    irreversible_effect: Her official access is revoked.\n    payoff_window:\n      start_chapter: 3\n      end_chapter: 4\nexpected:\n  valid_codes: []\n  invalid_codes:\n    - incomplete-decision-consequence\n    - invalid-payoff-window\n',
    'evals/v1-3-release/guardrail-promotion.yaml': 'schema_version: 1.0.0\nid: guardrail-promotion\nkind: guardrail-promotion\ninput:\n  below_threshold:\n    chapters:\n      - 4\n      - 4\n    milestone_reviews:\n      - act-1\n  chapter_threshold:\n    chapters:\n      - 4\n      - 9\n      - 14\n    milestone_reviews: []\n  review_threshold:\n    chapters: []\n    milestone_reviews:\n      - act-1\n      - midpoint\nexpected:\n  below_eligible: false\n  chapter_eligible: true\n  review_eligible: true\n',
    'evals/v1-3-release/influence-translation.yaml': 'schema_version: 1.0.0\nid: influence-translation\nkind: influence-translation\ninput:\n  reference: Private Reference Author — Private Reference Book\n  derived_traits:\n    - compressed causal transitions\n    - controlled interiority\n  safe_profile: Use compressed causal transitions and controlled interiority.\n  unsafe_profile: Write like Private Reference Author.\nexpected:\n  safe_codes: []\n  unsafe_codes:\n    - direct-imitation\n    - raw-reference\n',
    'evals/v1-3-release/intentional-tradeoff.yaml': 'schema_version: 1.0.0\nid: intentional-tradeoff\nkind: intentional-tradeoff\ninput:\n  cluster_id: CLU-001\n  tradeoff_id: TRD-001\n  decision: accept-as-tradeoff\nexpected:\n  visible_tradeoff: true\n  approved_guardrail: false\n',
    'evals/v1-3-release/one-star-noise.yaml': 'schema_version: 1.0.0\nid: one-star-noise\nkind: one-star-noise\ninput:\n  observations:\n    - title: Comparable One\n      rating: 1\n    - title: Comparable Two\n      rating: 1\n    - title: Comparable Three\n      rating: 1\n    - title: Comparable Four\n      rating: 1\n    - title: Comparable Five\n      rating: 1\n    - title: Comparable Six\n      rating: 1\nexpected:\n  maximum_confidence: moderate\n',
    'evals/v1-3-release/praise-complaint-pairing.yaml': 'schema_version: 1.0.0\nid: praise-complaint-pairing\nkind: praise-complaint-pairing\ninput:\n  title: Comparable One\n  category: pacing-problem\nexpected:\n  negative_ids:\n    - OBS-001\n  positive_counterweights:\n    - OBS-002\n',
    'evals/v1-3-release/scene-diversity.yaml': 'schema_version: 1.0.0\nid: scene-diversity\nkind: scene-diversity\ninput:\n  engines:\n    - interview\n    - interview\n    - interview\n    - pursuit\nexpected:\n  finding_code: consecutive-scene-engine\n  chapters:\n    - 1\n    - 2\n    - 3\n',
    'evals/v1-3-release/voice-drift.yaml': 'schema_version: 1.0.0\nid: voice-drift\nkind: voice-drift\ninput:\n  baseline_text: Mara moved. She listened. "Go now," Jonah said.\n  current_text: Mara moved through the corridor and listened for the elevator before Jonah said, "Go now, before they see us."\nexpected:\n  changed_metrics:\n    - sentence_mean\n    - dialogue_ratio\n  interpretation: evidence-only\n',
    'evals/v1-3-release/writer-sample-precedence.yaml': 'schema_version: 1.0.0\nid: writer-sample-precedence\nkind: writer-sample-precedence\ninput:\n  shared_rule: Preserve clipped transitions.\n  influence_only: Use atmospheric compression.\nexpected:\n  winning_layer: writer-samples\n  must_include:\n    - Preserve clipped transitions.\n  prefer_include:\n    - Use atmospheric compression.\n',
    'tests/e2e/packed-clean-start.test.ts': 'import test from "node:test";\nimport assert from "node:assert/strict";\nimport { execFileSync } from "node:child_process";\nimport { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";\nimport { tmpdir } from "node:os";\nimport { join, resolve } from "node:path";\nimport { pathToFileURL } from "node:url";\n\ntest("the packed 1.3 extension initializes a clean project and keeps research optional", async () => {\n  const temp = mkdtempSync(join(tmpdir(), "novel-forge-v13-packed-start-"));\n  try {\n    const pack = JSON.parse(execFileSync("npm", ["pack", "--json", "--pack-destination", temp], { cwd: process.cwd() }).toString())[0];\n    execFileSync("tar", ["-xzf", join(temp, pack.filename), "-C", temp]);\n    const packageRoot = resolve(temp, "package");\n    execFileSync("npm", ["install", "--omit=dev", "--ignore-scripts", "--no-audit", "--no-fund"], { cwd: packageRoot, stdio: "pipe" });\n    const store = await import(pathToFileURL(resolve(packageRoot, "src", "project", "store.ts")).href);\n    const guide = await import(pathToFileURL(resolve(packageRoot, "src", "application", "guide.ts")).href);\n    const root = store.initializeProject(temp, { projectName: "Packed Start", projectType: "standalone", profile: "thriller" });\n    const project = store.readProject(root);\n    const screen = guide.buildGuideScreen(root);\n    assert.equal(project.novel_forge_version, "1.3.0");\n    assert.notEqual(screen.actions[0]?.id, "research");\n    assert.equal(screen.actions[0]?.kind, "primary");\n    assert.equal(screen.actions.find((action: { id: string }) => action.id === "research")?.kind, "secondary");\n    assert.equal(existsSync(resolve(packageRoot, "src", "evaluation", "v1-3-release.ts")), true);\n    assert.equal(JSON.parse(readFileSync(resolve(packageRoot, "package.json"), "utf8")).version, "1.3.0");\n  } finally {\n    rmSync(temp, { recursive: true, force: true });\n  }\n});\n',
    'tests/e2e/v1-3-release-journey.test.ts': 'import test from "node:test";\nimport assert from "node:assert/strict";\nimport { mkdtempSync, rmSync } from "node:fs";\nimport { tmpdir } from "node:os";\nimport { join } from "node:path";\nimport { runV13CleanProjectJourney } from "../../src/evaluation/v1-3-journey.js";\n\ntest("a clean project exercises the honest 1.3 evidence journey", async () => {\n  const parent = mkdtempSync(join(tmpdir(), "novel-forge-v13-journey-"));\n  try {\n    const report = await runV13CleanProjectJourney(parent);\n    assert.equal(report.initializedVersion, "1.3.0");\n    assert.deepEqual(report.invariantFailures, []);\n    for (const id of [\n      "initialize-project",\n      "research-snapshot",\n      "influence-preview-apply",\n      "planned-voice-experiment",\n      "research-item",\n      "public-review-identity-strip",\n      "strategy-graph-load",\n      "voice-audit-no-baseline",\n      "packaging-checklist",\n      "next-book-refusal",\n    ]) assert.ok(report.completedChecks.includes(id), id);\n    assert.ok(report.skippedChecks.some((item) => item.id === "accepted-voice-baseline" && /writer-selected prose/i.test(item.reason)));\n    assert.ok(report.skippedChecks.some((item) => item.id === "human-reader-merge" && /real human/i.test(item.reason)));\n    assert.ok(report.skippedChecks.some((item) => item.id === "docx-adoption" && /source file/i.test(item.reason)));\n  } finally {\n    rmSync(parent, { recursive: true, force: true });\n  }\n});\n',
    'tests/v1-3-release-checklist.test.ts': 'import test from "node:test";\nimport assert from "node:assert/strict";\nimport { verifyV13ReleaseTree } from "../scripts/verify-v1-3-release.js";\n\ntest("the repository tree satisfies the Novel Forge 1.3 release contract", () => {\n  const checks = verifyV13ReleaseTree(process.cwd());\n  assert.ok(checks.length >= 10);\n  assert.deepEqual(checks.filter((check) => !check.passed), []);\n  assert.equal(new Set(checks.map((check) => check.id)).size, checks.length);\n});\n',
    'tests/v1-3-release-evaluation.test.ts': 'import test from "node:test";\nimport assert from "node:assert/strict";\nimport { resolve } from "node:path";\nimport {\n  evaluateV13ReleaseFixture,\n  loadV13ReleaseFixtures,\n  type ReleaseEvaluationFixture,\n} from "../src/evaluation/v1-3-release.js";\n\ntest("all nine Novel Forge 1.3 release fixtures pass", () => {\n  const fixtures = loadV13ReleaseFixtures(resolve(process.cwd(), "evals", "v1-3-release"));\n  assert.equal(fixtures.length, 9);\n  const results = fixtures.map(evaluateV13ReleaseFixture);\n  assert.deepEqual(results.filter((result) => !result.passed), []);\n  assert.deepEqual(new Set(results.map((result) => result.kind)).size, 9);\n});\n\ntest("release evaluation reports evidence and failures without mutating input", () => {\n  const fixture: ReleaseEvaluationFixture = {\n    schema_version: "1.0.0",\n    id: "below-threshold",\n    kind: "guardrail-promotion",\n    input: { chapters: [4, 4], milestone_reviews: ["act-1"] },\n    expected: { eligible: true },\n  };\n  const before = structuredClone(fixture);\n  const result = evaluateV13ReleaseFixture(fixture);\n  assert.equal(result.passed, false);\n  assert.ok(result.evidence.length > 0);\n  assert.ok(result.failures.some((failure) => /eligible/i.test(failure)));\n  assert.deepEqual(fixture, before);\n});\n',
}
for path, content in FILES.items():
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
